# Generated by Django 3.1.7 on 2021-03-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidemeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
        migrations.RenameModel(
            old_name='Types_Activities',
            new_name='Type_Activity',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
