# Generated by Django 3.1.7 on 2021-03-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidemeapp', '0002_auto_20210306_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type_Activity',
        ),
    ]
