# Generated by Django 3.1.7 on 2021-03-06 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guidemeapp', '0003_delete_type_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='types',
            field=models.ManyToManyField(to='guidemeapp.Type'),
        ),
        migrations.AddField(
            model_name='rating',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='guidemeapp.activity'),
        ),
        migrations.AddField(
            model_name='rating',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
