# Generated by Django 3.2 on 2021-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidemeapp', '0005_auto_20210308_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.FilePathField(path='./images'),
        ),
    ]
