# Generated by Django 3.2 on 2021-04-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidemeapp', '0009_alter_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.CharField(default='mdi-border-none-variant', max_length=50),
        ),
    ]
